# Generated by Django 3.2.8 on 2021-11-13 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_urun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urun',
            old_name='isim',
            new_name='urun_isimi',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='guncelleme_tarih',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='link',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='olus_tarih',
        ),
        migrations.AlterField(
            model_name='urun',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='urun/'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='ust_kategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
