# Generated by Django 3.2.8 on 2021-11-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20211112_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urun',
            old_name='urun_isimi',
            new_name='urun_ismi',
        ),
        migrations.RemoveField(
            model_name='category',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='category',
            name='guncelleme_tarih',
        ),
        migrations.RemoveField(
            model_name='category',
            name='link',
        ),
        migrations.RemoveField(
            model_name='category',
            name='olus_tarih',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ust_kategory',
        ),
        migrations.AddField(
            model_name='urun',
            name='asil_fiyat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urun',
            name='indirim',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
