# Generated by Django 3.2.8 on 2021-11-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20211117_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='urun',
            name='image_gallery',
            field=models.ManyToManyField(help_text='resim galerisi', to='category.Post'),
        ),
    ]
