# Generated by Django 3.2.8 on 2021-11-20 04:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20211117_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
